spring:
  datasource:
    url: jdbc:mysql://rm-2ze31smx17n76u0iwpo.mysql.rds.aliyuncs.com:3306/shop_online?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1qaz@WSX

server:
  port: 8082

logging:
  com.mood.config: classpath:logback-spring.xml
  level: info
