spring:
  datasource:
    url: jdbc:mysql://120.77.3.111:3306/rebate_address?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

server:
  port: 8082

logging:
  com.mood.config: classpath:logback-spring.xml
  level: debug
